spring.application.name=EmergencySOSApp
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=aditya257661@gmail.com
spring.mail.password=owvb ysvw mnib gsqb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
fast2sms.api.key=eEx2kYPspTVH3Hko7EbCFsXhdKb841IXEjmPn4L2oqBjZKJ3GQhe2JMCGWfV